# Generated by Django 4.0.3 on 2022-04-07 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='updates',
            new_name='updated',
        ),
    ]
